import { NextRequest, NextResponse } from "next/server";

/**
 * POST /api/circle/challenge
 * Body: { method: string; params?: any[]; userToken: string; walletId: string }
 *
 * Bridges the circle-email wagmi connector's generic EIP-1193 provider
 * (lib/circleConnector.ts) to Circle's actual User-Controlled Wallets REST
 * API. Every write RPC method a wagmi/viem app can issue funnels through
 * here, gets mapped to the matching Circle "create a challenge" endpoint,
 * and returns { challengeId } for the Circle Web SDK's execute() to open
 * its PIN/biometric confirmation UI against.
 *
 *   eth_sendTransaction   -> POST /v1/w3s/user/transactions/contractExecution
 *   personal_sign         -> POST /v1/w3s/user/sign/message
 *   eth_signTypedData_v4  -> POST /v1/w3s/user/sign/typedData
 *
 * Docs:
 *  https://developers.circle.com/api-reference/wallets/user-controlled-wallets/create-user-contract-execution-transaction
 *  https://developers.circle.com/w3s/initiate-a-signature-request
 */

const CIRCLE_API_BASE = "https://api.circle.com/v1/w3s";

class CircleApiError extends Error {
  status: number;
  code?: number;
  constructor(message: string, status: number, code?: number) {
    super(message);
    this.status = status;
    this.code = code;
  }
}

interface ChallengeResult {
  challengeId: string;
}

export async function POST(req: NextRequest) {
  const { method, params, userToken, walletId } = await req.json();

  if (!userToken) {
    return NextResponse.json({ error: "Missing Circle session (userToken)" }, { status: 400 });
  }
  if (!walletId) {
    return NextResponse.json({ error: "Missing Circle session (walletId)" }, { status: 400 });
  }
  if (!method) {
    return NextResponse.json({ error: "Missing RPC method to bridge" }, { status: 400 });
  }

  if (!process.env.CIRCLE_API_KEY) {
    return NextResponse.json(
      { error: "Circle API key not configured on this environment yet" },
      { status: 501 }
    );
  }

  try {
    let result: ChallengeResult;

    switch (method) {
      case "eth_sendTransaction":
        result = await createTransactionChallenge(userToken, walletId, params);
        break;
      case "personal_sign":
        result = await createMessageSignChallenge(userToken, walletId, params);
        break;
      case "eth_signTypedData_v4":
        result = await createTypedDataSignChallenge(userToken, walletId, params);
        break;
      default:
        return NextResponse.json({ error: `Unsupported RPC method for Circle bridging: "${method}"` }, { status: 400 });
    }

    return NextResponse.json(result);
  } catch (err: any) {
    if (err instanceof CircleApiError) {
      return NextResponse.json({ error: err.message, code: err.code }, { status: err.status });
    }
    return NextResponse.json({ error: err?.message || "Could not create Circle challenge" }, { status: 502 });
  }
}

async function circlePost(path: string, userToken: string, body: Record<string, unknown>): Promise<ChallengeResult> {
  const res = await fetch(`${CIRCLE_API_BASE}${path}`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${process.env.CIRCLE_API_KEY}`,
      "X-User-Token": userToken,
    },
    body: JSON.stringify(body),
  });

  const payload = await res.json().catch(() => null);

  if (!res.ok) {
    throw new CircleApiError(payload?.message || `Circle rejected the request to ${path}`, res.status, payload?.code);
  }

  const challengeId = payload?.data?.challengeId;
  if (!challengeId) {
    throw new CircleApiError(`Unexpected response from Circle for ${path}`, 502);
  }

  return { challengeId };
}

/**
 * eth_sendTransaction params per EIP-1193: [{ from, to, data, value, ... }].
 * Mapped straight to Circle's contractExecution endpoint using the raw
 * `data` as callData — Circle's own guidance explicitly recommends this
 * over reconstructing abiFunctionSignature/abiParameters when the calldata
 * was generated by a trusted library like viem (which wagmi's writeContract
 * always uses), which is exactly how every transaction in this app is built.
 */
async function createTransactionChallenge(userToken: string, walletId: string, params: any[] | undefined): Promise<ChallengeResult> {
  const tx = params?.[0];
  if (!tx?.to) {
    throw new CircleApiError("eth_sendTransaction params missing a destination address", 400);
  }

  const body: Record<string, unknown> = {
    idempotencyKey: crypto.randomUUID(),
    walletId,
    contractAddress: tx.to,
    feeLevel: "MEDIUM",
  };

  if (tx.data && tx.data !== "0x") {
    body.callData = tx.data;
  }

  // Native-value calls: this app never sends one today (every transaction is
  // either a zero-value contract call or an ERC20 transfer encoded as
  // calldata), so the conversion below only kicks in if a nonzero hex value
  // ever does show up, rather than silently mis-handling it.
  if (tx.value && tx.value !== "0x0" && tx.value !== "0x") {
    const weiValue = BigInt(tx.value);
    if (weiValue > 0n) {
      // Arc's native gas token (USDC) uses 6 decimals.
      body.amount = (Number(weiValue) / 1_000_000).toString();
    }
  }

  return circlePost("/user/transactions/contractExecution", userToken, body);
}

/**
 * personal_sign params per EIP-1193: [hexMessage, address]. The message is
 * always hex-encoded at this layer, so we pass encodedByHex: true rather
 * than re-decoding it ourselves.
 */
async function createMessageSignChallenge(userToken: string, walletId: string, params: any[] | undefined): Promise<ChallengeResult> {
  const message = params?.[0];
  if (!message) {
    throw new CircleApiError("personal_sign params missing the message to sign", 400);
  }

  return circlePost("/user/sign/message", userToken, {
    walletId,
    message,
    encodedByHex: true,
  });
}

/**
 * eth_signTypedData_v4 params per EIP-1193: [address, typedDataJsonString].
 * Circle's `data` field is documented as exactly this JSON string, so it's
 * passed straight through.
 */
async function createTypedDataSignChallenge(userToken: string, walletId: string, params: any[] | undefined): Promise<ChallengeResult> {
  const data = params?.[1];
  if (!data) {
    throw new CircleApiError("eth_signTypedData_v4 params missing the typed data payload", 400);
  }

  return circlePost("/user/sign/typedData", userToken, {
    walletId,
    data,
  });
}
