/**
 * Hand-written ABI subset for P2PEscrow.sol — kept in sync manually with the
 * contract in /contracts/src/P2PEscrow.sol. Once the contract is compiled,
 * swap this for the generated artifact ABI (out/P2PEscrow.sol/P2PEscrow.json)
 * to guarantee drift-free typing.
 */
export const p2pEscrowAbi = [
  {
    type: "function",
    name: "createOffer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "side", type: "uint8" },
      { name: "token", type: "address" },
      { name: "fiatCurrency", type: "string" },
      { name: "rate", type: "uint256" },
      { name: "minAmount", type: "uint256" },
      { name: "maxAmount", type: "uint256" },
      { name: "terms", type: "string" },
    ],
    outputs: [{ name: "offerId", type: "uint256" }],
  },
  {
    type: "function",
    name: "pauseOffer",
    stateMutability: "nonpayable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "resumeOffer",
    stateMutability: "nonpayable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "recordOfferView",
    stateMutability: "nonpayable",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptOffer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "amount", type: "uint256" },
      { name: "fiatAmount", type: "uint256" },
      { name: "useAlternateTimer", type: "bool" },
    ],
    outputs: [{ name: "tradeId", type: "uint256" }],
  },
  {
    type: "function",
    name: "markFiatSent",
    stateMutability: "nonpayable",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "releaseFunds",
    stateMutability: "nonpayable",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelTrade",
    stateMutability: "nonpayable",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "raiseDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tradeId", type: "uint256" },
      { name: "evidenceURI", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "rateTrade",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tradeId", type: "uint256" },
      { name: "stars", type: "uint8" },
      { name: "comment", type: "string" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "hasRated",
    stateMutability: "view",
    inputs: [
      { name: "", type: "uint256" },
      { name: "", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "getTradeRatings",
    stateMutability: "view",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple[]",
        components: [
          { name: "stars", type: "uint8" },
          { name: "comment", type: "string" },
          { name: "rater", type: "address" },
          { name: "timestamp", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getOffer",
    stateMutability: "view",
    inputs: [{ name: "offerId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "merchant", type: "address" },
          { name: "side", type: "uint8" },
          { name: "token", type: "address" },
          { name: "fiatCurrency", type: "string" },
          { name: "rate", type: "uint256" },
          { name: "minAmount", type: "uint256" },
          { name: "maxAmount", type: "uint256" },
          { name: "terms", type: "string" },
          { name: "active", type: "bool" },
          { name: "paused", type: "bool" },
          { name: "views", type: "uint256" },
          { name: "tradesCount", type: "uint256" },
          { name: "volume", type: "uint256" },
          { name: "createdAt", type: "uint256" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "getTrade",
    stateMutability: "view",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "id", type: "uint256" },
          { name: "offerId", type: "uint256" },
          { name: "token", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "makerFeeAmount", type: "uint256" },
          { name: "takerFeeAmount", type: "uint256" },
          { name: "cryptoBuyer", type: "address" },
          { name: "cryptoSeller", type: "address" },
          { name: "fiatAmount", type: "uint256" },
          { name: "fiatCurrency", type: "string" },
          { name: "status", type: "uint8" },
          { name: "lockedAt", type: "uint256" },
          { name: "timerDuration", type: "uint256" },
          { name: "fiatMarkedAt", type: "uint256" },
          { name: "disputeRaised", type: "bool" },
          { name: "evidenceURI", type: "string" },
        ],
      },
    ],
  },
  {
    type: "function",
    name: "timeRemaining",
    stateMutability: "view",
    inputs: [{ name: "tradeId", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextOfferId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "nextTradeId",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isApprovedMerchant",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "makerFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "takerFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "defaultTimer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "alternateTimer",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "updateOffer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "offerId", type: "uint256" },
      { name: "rate", type: "uint256" },
      { name: "minAmount", type: "uint256" },
      { name: "maxAmount", type: "uint256" },
      { name: "terms", type: "string" },
    ],
    outputs: [],
  },

  // --- Merchant application / approval ---
  { type: "function", name: "applyForMerchant", stateMutability: "nonpayable", inputs: [], outputs: [] },
  {
    type: "function",
    name: "approveMerchant",
    stateMutability: "nonpayable",
    inputs: [{ name: "applicant", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "rejectMerchant",
    stateMutability: "nonpayable",
    inputs: [{ name: "applicant", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "restrictMerchant",
    stateMutability: "nonpayable",
    inputs: [{ name: "merchant", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "isPendingMerchant",
    stateMutability: "view",
    inputs: [{ name: "", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // --- Dispute resolution (arbiter) ---
  {
    type: "function",
    name: "resolveDispute",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tradeId", type: "uint256" },
      { name: "amountToBuyer", type: "uint256" },
    ],
    outputs: [],
  },

  // --- Owner / admin configuration ---
  {
    type: "function",
    name: "addArbiter",
    stateMutability: "nonpayable",
    inputs: [{ name: "arbiter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "removeArbiter",
    stateMutability: "nonpayable",
    inputs: [{ name: "arbiter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSupportedToken",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setSupportedFiat",
    stateMutability: "nonpayable",
    inputs: [
      { name: "currency", type: "string" },
      { name: "enabled", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setMakerFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeBps", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setTakerFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeBps", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSendFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeBps", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setAirtimeFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeBps", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setTimers",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newDefaultTimer", type: "uint256" },
      { name: "newAlternateTimer", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "sendFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "treasury",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "airtimeFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "hasRole",
    stateMutability: "view",
    inputs: [
      { name: "role", type: "bytes32" },
      { name: "account", type: "address" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "OWNER_ROLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "ARBITER_ROLE",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "event",
    name: "MerchantApplied",
    inputs: [{ name: "applicant", type: "address", indexed: true }],
  },
  {
    type: "event",
    name: "DisputeRaised",
    inputs: [
      { name: "tradeId", type: "uint256", indexed: true },
      { name: "by", type: "address", indexed: true },
      { name: "evidenceURI", type: "string", indexed: false },
    ],
  },
  {
    type: "event",
    name: "OfferCreated",
    inputs: [
      { name: "offerId", type: "uint256", indexed: true },
      { name: "merchant", type: "address", indexed: true },
      { name: "side", type: "uint8", indexed: false },
      { name: "token", type: "address", indexed: false },
      { name: "fiatCurrency", type: "string", indexed: false },
      { name: "rate", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TradeLocked",
    inputs: [
      { name: "tradeId", type: "uint256", indexed: true },
      { name: "offerId", type: "uint256", indexed: true },
      { name: "cryptoBuyer", type: "address", indexed: true },
      { name: "cryptoSeller", type: "address", indexed: false },
      { name: "amount", type: "uint256", indexed: false },
      { name: "makerFeeAmount", type: "uint256", indexed: false },
      { name: "takerFeeAmount", type: "uint256", indexed: false },
      { name: "timerDuration", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TradeReleased",
    inputs: [
      { name: "tradeId", type: "uint256", indexed: true },
      { name: "to", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
  },
] as const;

/** Minimal ERC20 ABI needed for allowance, approve, and direct transfers (send/airtime flows). */
export const erc20AllowanceAbi = [
  {
    type: "function",
    name: "transfer",
    stateMutability: "nonpayable",
    inputs: [
      { name: "to", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },
] as const;
